/*
 * Licensed to The Apereo Foundation under one or more contributor license
 * agreements. See the NOTICE file distributed with this work for additional
 * information regarding copyright ownership.
 *
 *
 * The Apereo Foundation licenses this file to you under the Educational
 * Community License, Version 2.0 (the "License"); you may not use this file
 * except in compliance with the License. You may obtain a copy of the License
 * at:
 *
 *   http://opensource.org/licenses/ecl2.txt
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
 * WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.  See the
 * License for the specific language governing permissions and limitations under
 * the License.
 *
 */
package org.opencastproject.publication.api;

import org.opencastproject.mediapackage.MediaPackage;
import org.opencastproject.mediapackage.MediaPackageElementFlavor;
import org.opencastproject.security.api.Organization;

import java.util.List;
import java.util.Optional;

public interface EngagePublicationService {

  /** Name constant for the 'merge' strategy **/
  String PUBLISH_STRATEGY_MERGE = "merge";

  /** Name constant for the 'default' 'strategy **/
  String PUBLISH_STRATEGY_DEFAULT = "default";

  String ENGAGE_URL_PROPERTY = "org.opencastproject.engage.ui.url";

  /** Path the REST endpoint which will re-direct users to the currently configured video player **/
  String PLAYER_PATH = "/play/";

  // TODO This signature is generated by IntelliJ, I'm not saying it's nice.
  //   Maybe one wants to reorder it, or even change some of the types
  //   (which might require extracting some of or pulling in more of the code
  //   that parses/processes the inputs).
  //   This should depend on what the different calling sites naturally want to pass in here,
  //   i.e. what we put in the workflow job and the "direct update service" configuration.
  /** TODO JavaDoc */
  Optional<MediaPackage> publish(MediaPackage mediaPackage, String[] sourceDownloadFlavors, String[] sourceDownloadTags,
          String[] sourceStreamingFlavors, String[] sourceStreamingTags, String republishStrategy,
          boolean checkAvailability, MediaPackageElementFlavor downloadSubflavor, String[] targetDownloadTags,
          MediaPackageElementFlavor streamingSubflavor, String[] targetStreamingTags,
          List<MediaPackageElementFlavor> mergeForceFlavors, List<MediaPackageElementFlavor> addForceFlavors,
          Organization organization, boolean sync) throws PublicationException;
}
